export const FETCH_CLIPS = 'FETCH_CLIPS';
export const FETCH_CLIPS_SUCCESS = 'FETCH_CLIPS_SUCCESS';
export const FETCH_CLIPS_FAILED = 'FETCH_CLIPS_FAILED';

export const FETCH_STREAMERS = 'FETCH_STREAMERS';
export const FETCH_STREAMERS_SUCCESS = 'FETCH_STREAMERS_SUCCESS';
export const FETCH_STREAMERS_FAILED = 'FETCH_STREAMERS_FAILED';

export const FETCH_MATCHES = 'FETCH_MATCHES';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_FAILED = 'FETCH_MATCHES_FAILED';

export const FETCH_MATCH = 'FETCH_MATCH';
export const FETCH_MATCH_SUCCESS = 'FETCH_MATCH_SUCCESS';
export const FETCH_MATCH_FAILED = 'FETCH_MATCH_FAILED';

export const SHOW_TOAST = 'SHOW_TOAST';
export const KILL_TOAST = 'KILL_TOAST';

export const UPDATE_STREAM_URL = 'UPDATE_STREAM_URL';
export const SET_SELECTED_CLIP = 'SET_SELECTED_CLIP';
export const SELECT_MATCH = 'SELECT_MATCH';
